spring:
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:postgresql://localhost:5432/application
    username: postgres
    password: postgres
    driverClassName: org.postgresql.Driver
 application:
   name: naumov